package com.xlk.mapper;

import com.xlk.pojo.Log;
import com.xlk.pojo.LogExample;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
@Mapper
public interface LogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_log
     *
     * @mbg.generated Tue Mar 08 11:59:08 CST 2022
     */
    long countByExample(LogExample example);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_log
     *
     * @mbg.generated Tue Mar 08 11:59:08 CST 2022
     */
    int deleteByExample(LogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_log
     *
     * @mbg.generated Tue Mar 08 11:59:08 CST 2022
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_log
     *
     * @mbg.generated Tue Mar 08 11:59:08 CST 2022
     */
    int insert(Log record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_log
     *
     * @mbg.generated Tue Mar 08 11:59:08 CST 2022
     */
    int insertSelective(Log record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_log
     *
     * @mbg.generated Tue Mar 08 11:59:08 CST 2022
     */
    List<Log> selectByExample(LogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_log
     *
     * @mbg.generated Tue Mar 08 11:59:08 CST 2022
     */
    Log selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_log
     *
     * @mbg.generated Tue Mar 08 11:59:08 CST 2022
     */
    int updateByExampleSelective(@Param("record") Log record, @Param("example") LogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_log
     *
     * @mbg.generated Tue Mar 08 11:59:08 CST 2022
     */
    int updateByExample(@Param("record") Log record, @Param("example") LogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_log
     *
     * @mbg.generated Tue Mar 08 11:59:08 CST 2022
     */
    int updateByPrimaryKeySelective(Log record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_log
     *
     * @mbg.generated Tue Mar 08 11:59:08 CST 2022
     */
    int updateByPrimaryKey(Log record);
}