package com.xlk.pojo;

import java.util.Date;

public class Log {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column platform_log.id
     *
     * @mbg.generated Tue Mar 08 11:59:08 CST 2022
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column platform_log.login_ip
     *
     * @mbg.generated Tue Mar 08 11:59:08 CST 2022
     */
    private String loginIp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column platform_log.login_name
     *
     * @mbg.generated Tue Mar 08 11:59:08 CST 2022
     */
    private String loginName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column platform_log.login_msg
     *
     * @mbg.generated Tue Mar 08 11:59:08 CST 2022
     */
    private String loginMsg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column platform_log.created_by
     *
     * @mbg.generated Tue Mar 08 11:59:08 CST 2022
     */
    private Long createdBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column platform_log.created_date
     *
     * @mbg.generated Tue Mar 08 11:59:08 CST 2022
     */
    private Date createdDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column platform_log.last_modified_by
     *
     * @mbg.generated Tue Mar 08 11:59:08 CST 2022
     */
    private Long lastModifiedBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column platform_log.last_modified
     *
     * @mbg.generated Tue Mar 08 11:59:08 CST 2022
     */
    private Date lastModified;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column platform_log.owner
     *
     * @mbg.generated Tue Mar 08 11:59:08 CST 2022
     */
    private String owner;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column platform_log.id
     *
     * @return the value of platform_log.id
     *
     * @mbg.generated Tue Mar 08 11:59:08 CST 2022
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column platform_log.id
     *
     * @param id the value for platform_log.id
     *
     * @mbg.generated Tue Mar 08 11:59:08 CST 2022
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column platform_log.login_ip
     *
     * @return the value of platform_log.login_ip
     *
     * @mbg.generated Tue Mar 08 11:59:08 CST 2022
     */
    public String getLoginIp() {
        return loginIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column platform_log.login_ip
     *
     * @param loginIp the value for platform_log.login_ip
     *
     * @mbg.generated Tue Mar 08 11:59:08 CST 2022
     */
    public void setLoginIp(String loginIp) {
        this.loginIp = loginIp == null ? null : loginIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column platform_log.login_name
     *
     * @return the value of platform_log.login_name
     *
     * @mbg.generated Tue Mar 08 11:59:08 CST 2022
     */
    public String getLoginName() {
        return loginName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column platform_log.login_name
     *
     * @param loginName the value for platform_log.login_name
     *
     * @mbg.generated Tue Mar 08 11:59:08 CST 2022
     */
    public void setLoginName(String loginName) {
        this.loginName = loginName == null ? null : loginName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column platform_log.login_msg
     *
     * @return the value of platform_log.login_msg
     *
     * @mbg.generated Tue Mar 08 11:59:08 CST 2022
     */
    public String getLoginMsg() {
        return loginMsg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column platform_log.login_msg
     *
     * @param loginMsg the value for platform_log.login_msg
     *
     * @mbg.generated Tue Mar 08 11:59:08 CST 2022
     */
    public void setLoginMsg(String loginMsg) {
        this.loginMsg = loginMsg == null ? null : loginMsg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column platform_log.created_by
     *
     * @return the value of platform_log.created_by
     *
     * @mbg.generated Tue Mar 08 11:59:08 CST 2022
     */
    public Long getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column platform_log.created_by
     *
     * @param createdBy the value for platform_log.created_by
     *
     * @mbg.generated Tue Mar 08 11:59:08 CST 2022
     */
    public void setCreatedBy(Long createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column platform_log.created_date
     *
     * @return the value of platform_log.created_date
     *
     * @mbg.generated Tue Mar 08 11:59:08 CST 2022
     */
    public Date getCreatedDate() {
        return createdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column platform_log.created_date
     *
     * @param createdDate the value for platform_log.created_date
     *
     * @mbg.generated Tue Mar 08 11:59:08 CST 2022
     */
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column platform_log.last_modified_by
     *
     * @return the value of platform_log.last_modified_by
     *
     * @mbg.generated Tue Mar 08 11:59:08 CST 2022
     */
    public Long getLastModifiedBy() {
        return lastModifiedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column platform_log.last_modified_by
     *
     * @param lastModifiedBy the value for platform_log.last_modified_by
     *
     * @mbg.generated Tue Mar 08 11:59:08 CST 2022
     */
    public void setLastModifiedBy(Long lastModifiedBy) {
        this.lastModifiedBy = lastModifiedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column platform_log.last_modified
     *
     * @return the value of platform_log.last_modified
     *
     * @mbg.generated Tue Mar 08 11:59:08 CST 2022
     */
    public Date getLastModified() {
        return lastModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column platform_log.last_modified
     *
     * @param lastModified the value for platform_log.last_modified
     *
     * @mbg.generated Tue Mar 08 11:59:08 CST 2022
     */
    public void setLastModified(Date lastModified) {
        this.lastModified = lastModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column platform_log.owner
     *
     * @return the value of platform_log.owner
     *
     * @mbg.generated Tue Mar 08 11:59:08 CST 2022
     */
    public String getOwner() {
        return owner;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column platform_log.owner
     *
     * @param owner the value for platform_log.owner
     *
     * @mbg.generated Tue Mar 08 11:59:08 CST 2022
     */
    public void setOwner(String owner) {
        this.owner = owner == null ? null : owner.trim();
    }
}